# Generated by Django 5.1.4 on 2024-12-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=100)),
                ('numero_conta', models.CharField(max_length=10, unique=True)),
                ('senha', models.CharField(max_length=4)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContaPoupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_poupanca', models.FloatField(default=0.0)),
                ('conta_corrente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_poupanca', to='appProjBanco.contacorrente')),
            ],
        ),
    ]
