# Generated by Django 5.1.4 on 2024-12-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjBanco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='saldo',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='appProjBanco.contacorrente')),
            ],
        ),
        migrations.DeleteModel(
            name='ContaPoupanca',
        ),
    ]
